name = "SintPowerCase"
uuid = "dcf425a8-86bf-4135-b17a-04ddca2f3b37"
authors = ["Sigurd Hofsmo Jakobsen <sigurd.jakobsen@sintef.no>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CSV = "0.10"
DataFrames = "1.6.1"
SparseArrays = "1.10"
TOML = "1.0.3"
julia = "1.10"
